name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project. >> test.txt
      - uses: actions/upload-artifact@master
        with:
          name: Artifact
          path: test.txt
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - uses: actions/download-artifact@master
        with:
          name: Artifact
          path: test.txt

      - name: See Content of the file
        run: |
          echo "Content of the file:"
          cat test.txt
